"""Mapeamento canônico das 87 colunas da Tabela Mestra de Tracking."""

from __future__ import annotations

# Chaves internas → nome exato no Excel
COL = {
    "waybill": "运单号(Número do Waybill)",
    "scan": "扫描单号(Número de ordem de escaneamento)",
    "order": "安骏订单号(Número do pedido Anjun)",
    "package_type": "包裹类型(Tipo do pacote)",
    "status": "运单状态(Status do Pacote)",
    "last_track_time": "最新轨迹时间(Último data de rastreio)",
    "last_track": "最新轨迹内容(Último rastreio)",
    "last_point": "最新轨迹网点(Último ponto de rastreio)",
    "issue_reason": "问题件原因(Motivo da Ocorrência)",
    "tag": "标签(Tag)",
    "order_type": "订单类型(Tipo do pedido)",
    "dest_state": "收件人州(Estado do destinatário)",
    "dest_city": "收件人城市(Cidade do destinatário)",
    "dest_neighborhood": "收件人区(Bairro do destinatário)",
    "dest_street": "收件人街道(Rua do destinatário)",
    "dest_cep": "收件人邮编(CEP do destinatário)",
    "zone": "区域(Zona)",
    "city_type": "城镇类型(Tipo de cidade)",
    "origin_state": "发件人州(Estado de origem)",
    "origin_city": "发件人城市(Cidade do remetente)",
    "origin_hierarchy": "发件地区类型(Hierarquia urbana de origem)",
    "client": "客户名称(Nome do cliente)",
    "merchant": "商户名称(Nome do Cliente Merchant)",
    "region": "大区(Região)",
    "pre_point": "预派送网点(Ponto de Pré-entrega)",
    "entry_point": "实际入库网点(Ponto de entrada)",
    "entry_state": "实际入库网点州(Estado do ponto de entrada)",
    "delivery_point": "实际派送网点(Ponto de entrega)",
    "courier": "派送员(entregador)",
    "collect_type": "揽收类型(Tipo de coleta)",
    "sign_type": "签收类型(Tipo de assinatura)",
    "recipient_type": "签收人类型(Tipo do destinatário)",
    "recipient_relation": "签收人关系(Relação do Destinatário)",
    "created_at": "订单创建时间(Criação de pedido)",
    "client_warehouse_out": "客户出仓时间(Saída do armazém do cliente)",
    "lm_collect": "末端揽收时间(Coleta de LM)",
    "collect_load": "揽收装车时间(Carregamento da coleta)",
    "collect_next": "揽收下一站(Próxima Parada da Coleta)",
    "collect_duration_h": "揽收时长(小时)(Range rover duração (horas))",
    "collect_transit_h": "揽收运输时长(H)(Tempo de Transporte de Coleta(H))",
    "collect_seal": "揽收封车时间(Fechamento do veículo da coleta)",
    "hub1_unseal": "HUB1解封车时间(Abertura do veículo do HUB1)",
    "hub1_in": "一级分拨到件时间(Entrada no centro nível 01)",
    "hub1_center": "实际到件分拨中心(Centro real de chegada)",
    "hub1_out": "一级分拨发件时间(Saída do centro nível 01)",
    "hub1_next": "下一站(Próximo ponto)",
    "hub1_seal": "HUB1封车时间(Fechamento do veículo do HUB1)",
    "hub1_op_h": "一级分拨操作时长(Duração da operação do centro nível 01)",
    "hub2_unseal": "HUB2解封车时间(Abertura do veículo do HUB2)",
    "hub2_in": "二级分拨到件时间(Entrada no centro nível 02)",
    "hub2_center": "实际到件分拨中心(Centro real de chegada).1",
    "hub2_out": "二级分拨发件时间(Saída do centro nível 02)",
    "hub2_next": "下一站(Próximo ponto).1",
    "hub2_seal": "HUB2封车时间(Fechamento do veículo do HUB2)",
    "hub2_op_h": "二级分拨操作时长(Duração da operação do centro nível 02)",
    "hub3_unseal": "HUB3解封车时间(Abertura do veículo do HUB3)",
    "hub3_in": "三级分拨到件时间(Entrada no centro nível 03)",
    "hub3_center": "实际到件分拨中心(Centro real de chegada).2",
    "hub3_out": "三级分拨发件时间(Saída do centro nível 03)",
    "hub3_next": "下一站(Próximo ponto).2",
    "hub3_seal": "HUB3封车时间(Tempo de bloqueio do HUB3)",
    "hub3_op_h": "三级分拨操作时长(Duração da operação do centro de distribuição nível 03)",
    "base_unseal": "网点解封车时间(Tempo de Desbloquear o veículo)",
    "base_inbound": "网点入库时间(Tempo de inbound no ponto)",
    "base_dispatch": "网点派件时间(Hora de Entrega do Ponto)",
    "attempt_1": "第一次派送时间(Primeiro horário de entrega)",
    "attempt_2": "第二次派送时间(Segundo horário de entrega)",
    "attempt_3": "第三次派送时间(Terceiro horário de entrega)",
    "first_dispatch": "首派时间(Hora do Primeira Entrega)",
    "signed_at": "签收时间(Tempo de Assinatura)",
    "base_dispatch_h": "网点派件时长(H)(Tempo de Despacho do Ponto(H))",
    "dispatch_transit_h": "派件在途时长(H)(Tempo de Trânsito de Despacho(H))",
    "first_dispatch_h": "首派所用时长(Duração do Primeira Entrega)",
    "base_sign_h": "网点签收时长(H)(Tempo de Assinatura do Ponto(H))",
    "total_sign_h": "总签收时长(H)(Tempo Total de Assinatura(H))",
    "hub1_transit_h": "HUB1发出运输时长(H)(Tempo de Transporte HUB1(H))",
    "hub2_transit_h": "HUB2发出运输时长(H)(Tempo de Transporte HUB2(H))",
    "hub3_transit_h": "HUB3发出运输时长(H)(Tempo de Transporte HUB3(H))",
    "sla_days": "客户时效要求天数(Dias de prazo requisitados por cliente)",
    "due_at": "理应送达时间(Horário em que deve ser entregue)",
    "closed_loop_days": "客户要求闭环天数(O cliente pede o número de dias do ciclo fechado)",
    "closed_loop_at": "客户要求闭环时间(Cliente solicita tempo de ciclo fechado)",
    "delay_h": "超时时长(H)(Duração do Atraso)",
    "delay_days": "超时天数(Dias de Atraso)",
    "issue_registered_at": "问题件登记时间(Hora de registro do item com problema)",
    "issue_point": "问题件登记网点(Ponto de registro de problema)",
    "first_return_at": "网点首次退件时间(Data da primeira devolução do ponto de serviço)",
}

# Labels curtos em PT para UI
LABEL = {
    "waybill": "Waybill",
    "status": "Status",
    "last_track_time": "Último rastreio",
    "last_track": "Conteúdo do rastreio",
    "last_point": "Ponto atual",
    "issue_reason": "Motivo ocorrência",
    "order_type": "Tipo pedido",
    "dest_state": "UF",
    "dest_city": "Cidade",
    "dest_neighborhood": "Bairro",
    "dest_cep": "CEP",
    "zone": "Zona",
    "city_type": "Tipo cidade",
    "client": "Cliente",
    "merchant": "Merchant",
    "region": "Região",
    "pre_point": "Ponto pré-entrega",
    "entry_point": "Ponto entrada",
    "delivery_point": "Ponto entrega",
    "courier": "Entregador",
    "attempt_1": "1ª tentativa",
    "attempt_2": "2ª tentativa",
    "attempt_3": "3ª tentativa",
    "signed_at": "Assinatura",
    "hub1_op_h": "Op. HUB1 (H)",
    "hub2_op_h": "Op. HUB2 (H)",
    "hub3_op_h": "Op. HUB3 (H)",
    "base_dispatch_h": "Despacho base (H)",
    "hub1_transit_h": "Transporte HUB1 (H)",
    "hub2_transit_h": "Transporte HUB2 (H)",
    "hub3_transit_h": "Transporte HUB3 (H)",
    "sla_days": "SLA (dias)",
    "due_at": "Deveria entregar",
    "closed_loop_days": "Ciclo fechado (dias)",
    "closed_loop_at": "Deadline ciclo",
    "delay_h": "Atraso (H)",
    "delay_days": "Atraso (dias)",
    "issue_point": "Ponto problema",
    "created_at": "Criação",
    "days_to_closed_loop": "Dias até ciclo",
    "mesh_mismatch": "Erro de malha",
    "sop_violation": "Infração SOP",
    "delay_owner": "Responsável atraso",
    "hub_share_pct": "% tempo HUB",
    "base_share_pct": "% tempo Base",
    "risk_tier": "Nível risco",
    "cli_atraso_dias": "Atraso cliente (d)",
    "cli_resultado": "SLA cliente",
    "lm_atraso_dias": "Atraso last-mile (d)",
    "lm_resultado": "SLA last-mile",
    "lm_vencimento": "Venc. last-mile",
    "responsavel": "Responsável",
    "first_attempt": "1ª tentativa",
}

DATETIME_KEYS = [
    "last_track_time",
    "created_at",
    "client_warehouse_out",
    "lm_collect",
    "collect_load",
    "collect_seal",
    "hub1_unseal",
    "hub1_in",
    "hub1_out",
    "hub1_seal",
    "hub2_unseal",
    "hub2_in",
    "hub2_out",
    "hub2_seal",
    "hub3_unseal",
    "hub3_in",
    "hub3_out",
    "hub3_seal",
    "base_unseal",
    "base_inbound",
    "base_dispatch",
    "attempt_1",
    "attempt_2",
    "attempt_3",
    "first_dispatch",
    "signed_at",
    "due_at",
    "closed_loop_at",
    "issue_registered_at",
    "first_return_at",
]

NUMERIC_KEYS = [
    "collect_duration_h",
    "collect_transit_h",
    "hub1_op_h",
    "hub2_op_h",
    "hub3_op_h",
    "base_dispatch_h",
    "dispatch_transit_h",
    "first_dispatch_h",
    "base_sign_h",
    "total_sign_h",
    "hub1_transit_h",
    "hub2_transit_h",
    "hub3_transit_h",
    "sla_days",
    "closed_loop_days",
    "delay_h",
    "delay_days",
]

DELIVERED_STATUS = {"Pedido entregue"}
RETURNED_STATUS = {"Devolvido pelo ponto", "Recebido na devolução"}
IN_TRANSIT_STATUS = {
    "Em rota de entrega",
    "Recebido no ponto de entrega",
    "Expedido no hub",
    "Coletado",
    "Recebido no hub",
    "Pacote armazenado",
}
ANOMALY_STATUS = {"Pedido com anomalia"}
